"""
Three-phase project generator using Cerebras.

Phase 1: Plan     — architecture + file tree, category-aware, informed by source code
Phase 2: Generate — each file written individually with retry on 429
Phase 3: Validate — static review: broken imports, TODOs, name mismatches

No AI watermarks. No "generated by". Comments read like a human wrote them.
"""

import os
import json
import time
from cerebras.cloud.sdk import Cerebras

client = Cerebras(api_key=os.environ["CEREBRAS_API_KEY"])


# ── Helpers ───────────────────────────────────────────────────────────────────

def _call(messages: list, max_tokens: int = 2048, temperature: float = 0.5) -> str:
    """Call Cerebras with automatic retry on 429 rate limit."""
    max_retries = 5
    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model="gpt-oss-120b",
                messages=messages,
                max_tokens=max_tokens,
                temperature=temperature,
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            err = str(e)
            if "429" in err or "too_many_requests" in err or "queue_exceeded" in err:
                wait = (attempt + 1) * 8
                print(f"  [rate limit] waiting {wait}s before retry {attempt + 1}/{max_retries}...")
                time.sleep(wait)
                continue
            raise
    raise RuntimeError("Cerebras rate limit: max retries exceeded")


def _repair_json(raw: str) -> str:
    """
    Trim back to the last complete top-level closing brace/bracket so that
    a response truncated mid-stream by a token limit can still be parsed.
    Tries } first (objects), then ] (arrays).
    """
    for closing in ("}", "]"):
        idx = raw.rfind(closing)
        if idx != -1:
            candidate = raw[: idx + 1]
            try:
                json.loads(candidate)
                return candidate
            except json.JSONDecodeError:
                continue
    return raw


def _parse_json(raw: str) -> dict | list:
    """Strip markdown fences then parse JSON, with truncation recovery."""
    if raw.startswith("```"):
        parts = raw.split("```")
        raw = parts[1] if len(parts) > 1 else raw
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return json.loads(_repair_json(raw))


def _source_context_block(analysis: dict) -> str:
    ctx = analysis.get("_source_context", {})
    if not ctx:
        return ""
    block = "REFERENCE — ACTUAL SOURCE CODE FROM TRENDING REPO (read patterns, don't copy):\n"
    block += f"\nDirectory structure:\n{ctx.get('tree_summary', '')[:800]}\n"
    for path, content in ctx.get("source_files", {}).items():
        block += f"\n--- {path} ---\n{content[:1200]}\n"
    return block


# ── Category style profiles ───────────────────────────────────────────────────

CATEGORY_PROFILES = {
    "cli": {
        "language_hint": "Python or Go",
        "structure_hint": "cmd/ or cli/ for subcommands, internal/ for logic, pkg/ for reusable parts",
        "file_hints": [
            "main entry with argparse/cobra/click subcommands",
            "config reading from ~/.toolname/config.yaml",
            "rich terminal output with colors and progress bars",
            "shell completion script",
            "Makefile with build/install/test targets",
        ],
        "style": "Unix philosophy — do one thing well. Terse, fast, composable.",
    },
    "ai": {
        "language_hint": "Python",
        "structure_hint": "src/models/, src/pipelines/, src/utils/, examples/",
        "file_hints": [
            "model wrapper classes with clean .predict()/.run() interfaces",
            "pipeline orchestration with retry and timeout logic",
            "config via pydantic BaseSettings or dataclasses",
            "async support where it matters",
            "structured logging with loguru or structlog",
        ],
        "style": "Research-grade but practical. Type-annotated, async where needed.",
    },
    "llm": {
        "language_hint": "Python",
        "structure_hint": "src/agents/, src/prompts/, src/memory/, src/tools/",
        "file_hints": [
            "agent loop with tool calling and memory",
            "prompt templates as versioned files",
            "token counting and context window management",
            "streaming response handler",
            "tool registry with decorator-based registration",
        ],
        "style": "Production agent patterns. Real state management, real error handling.",
    },
    "agent": {
        "language_hint": "Python or TypeScript",
        "structure_hint": "src/agents/, src/tools/, src/memory/, src/runtime/",
        "file_hints": [
            "agent base class with plan/act/observe loop",
            "tool system with input validation and output schemas",
            "persistent memory store",
            "event bus for agent communication",
            "human-in-the-loop checkpoint system",
        ],
        "style": "Multi-agent aware. Clean separation between reasoning, tools, and memory.",
    },
    "web": {
        "language_hint": "TypeScript with Next.js or Python with FastAPI",
        "structure_hint": "app/ with proper routing, components/, lib/, api/",
        "file_hints": [
            "proper routing with layouts and nested routes",
            "reusable component library with typed props",
            "API layer with proper error handling",
            "environment variable validation at startup",
            "middleware for auth/logging/rate limiting",
        ],
        "style": "Production web patterns. Real error boundaries, real loading states.",
    },
    "api": {
        "language_hint": "Python (FastAPI) or TypeScript (Hono/Express)",
        "structure_hint": "src/routes/, src/middleware/, src/models/, src/services/",
        "file_hints": [
            "OpenAPI spec generated from code",
            "request/response validation with pydantic or zod",
            "proper HTTP status codes and error schema",
            "rate limiting middleware",
            "database migrations",
        ],
        "style": "REST best practices. Versioned endpoints. Proper 4xx/5xx handling.",
    },
    "developer-tools": {
        "language_hint": "Python, TypeScript, or Go",
        "structure_hint": "src/core/, src/plugins/, src/reporters/, bin/",
        "file_hints": [
            "plugin system for extensibility",
            "reporter interface (stdout, JSON, HTML)",
            "config file discovery walking up directory tree",
            "watch mode with file system events",
        ],
        "style": "DX-first. Zero config to start. Clear error messages with fix suggestions.",
    },
    "automation": {
        "language_hint": "Python",
        "structure_hint": "src/tasks/, src/triggers/, src/integrations/, src/scheduler/",
        "file_hints": [
            "task base class with retry, timeout, dependency support",
            "cron-style scheduler with timezone awareness",
            "webhook receiver for trigger events",
            "run history with status tracking",
            "dry-run mode",
        ],
        "style": "Reliable over clever. Idempotent tasks. Every run logged.",
    },
}

DEFAULT_PROFILE = {
    "language_hint": "Python or TypeScript",
    "structure_hint": "src/ for logic, tests/ for tests, docs/ for documentation",
    "file_hints": ["clean module separation", "proper error handling", "type annotations"],
    "style": "Clean, well-structured, production-quality code.",
}


def get_profile(category: str) -> dict:
    return CATEGORY_PROFILES.get(category, DEFAULT_PROFILE)


# ── Phase 1: Architecture plan ────────────────────────────────────────────────

PLAN_SYSTEM = """You are a senior software architect designing real open-source projects.
You have access to source code from a trending repo for reference — study its patterns.
Produce realistic file trees, not toy examples.
Respond ONLY with valid JSON. Always close every brace and bracket — never truncate."""


def plan_project(analysis: dict) -> dict:
    profile = get_profile(analysis["category"])
    source_block = _source_context_block(analysis)

    prompt = f"""Design a complete GitHub project file tree for this concept.

SOURCE INSPIRATION: {analysis['source_repo']} (⭐{analysis['source_stars']})
Concept: {analysis['concept']}
Problem solved: {analysis['problem_solved']}
Architecture pattern: {analysis.get('architecture_pattern', 'N/A')}
Key insights: {', '.join(analysis.get('key_implementation_insights', []))}
Your inspiration angle: {analysis['inspiration_angle']}
Category: {analysis['category']}

{source_block}

CATEGORY CONVENTIONS:
- Language: {profile['language_hint']}
- Structure: {profile['structure_hint']}
- Key files: {chr(10).join('  • ' + h for h in profile['file_hints'])}
- Style: {profile['style']}

REQUIREMENTS:
- 12-18 files across proper nested directories
- Always include: README.md, .github/workflows/ci.yml, dependency file, 2+ test files, 1 example
- "purpose" must be specific to THIS project
- Keep each "purpose" value short (under 12 words) to avoid hitting the token limit

Return ONLY this JSON:
{{
  "repo_name": "kebab-case-name",
  "description": "one-line GitHub description — what it does, no buzzwords",
  "language": "primary language",
  "topics": ["tag1", "tag2", "tag3", "tag4", "tag5"],
  "file_tree": [
    {{"path": "README.md", "purpose": "specific purpose"}},
    {{"path": "src/core/engine.py", "purpose": "specific purpose"}}
  ]
}}"""

    # FIX: was 2048 — too small for an 18-file plan with source context
    raw = _call(
        [{"role": "system", "content": PLAN_SYSTEM}, {"role": "user", "content": prompt}],
        max_tokens=3000,
        temperature=0.6,
    )
    return _parse_json(raw)


# ── Phase 2: File generation ──────────────────────────────────────────────────

FILE_SYSTEM = """You are a software engineer writing code for an open-source project.
Write complete, working code. Real logic, real error handling.
Comments should be brief and specific — only where non-obvious.
No AI phrases. No "generated by". No "This file was created to...".
Raw file content only — no markdown fences, no preamble."""


def generate_file(
    path: str,
    purpose: str,
    plan: dict,
    analysis: dict,
    already_written: dict,
) -> str:
    profile = get_profile(analysis["category"])
    source_block = _source_context_block(analysis)

    context = ""
    if already_written:
        context = "ALREADY WRITTEN FILES (match imports and naming):\n"
        for p, content in list(already_written.items())[-5:]:
            preview = content[:500].replace("\n", "\\n")
            context += f"\n// {p}\n{preview}...\n"

    prompt = f"""Project: {plan['repo_name']}
Language: {plan['language']}
Category: {analysis['category']}
Style: {profile['style']}

{source_block}

{context}

WRITE THIS FILE: {path}
Purpose: {purpose}

Rules:
- Complete working code, not a stub
- Match language, imports, and naming of existing files
- README.md: badges, install, usage with real examples, contributing section
- Test files: real assertions testing real behaviour
- CI yaml: working pipeline for this project's language and test framework
- Comments like a real dev: brief, only where non-obvious
- No "auto-generated", no generic phrases, no AI tells"""

    return _call(
        [{"role": "system", "content": FILE_SYSTEM}, {"role": "user", "content": prompt}],
        max_tokens=3000,
        temperature=0.35,
    )


# ── Phase 3: Validation pass ──────────────────────────────────────────────────

VALIDATE_SYSTEM = """You are a code reviewer doing a final pass before shipping.
Fix real problems only: broken imports, mismatched names, leftover stubs, README mismatches.
Respond ONLY with valid JSON. Always close every brace and bracket — never truncate."""


def validate_and_fix(files: dict, readme: str, plan: dict, analysis: dict) -> tuple[dict, str]:
    snapshot = f"=== README.md ===\n{readme[:500]}\n"
    for path, content in files.items():
        snapshot += f"\n=== {path} ===\n{content[:500]}\n"

    prompt = f"""Review this project for consistency issues.

Project: {plan['repo_name']} ({plan['language']})

FILES:
{snapshot}

Check ONLY for:
1. Import referencing a module/function that doesn't exist in the file tree
2. Function or class called in one file but named differently in another
3. Leftover `pass`, `raise NotImplementedError`, or bare `# TODO` stubs
4. Test file that doesn't import what it's testing
5. README describing a feature with a name that doesn't match the code

Return ONLY this JSON (empty list if no issues):
{{
  "fixes": [
    {{
      "path": "src/core/engine.py",
      "issue": "one-line description",
      "fixed_content": "complete corrected file content"
    }}
  ]
}}"""

    try:
        raw = _call(
            [{"role": "system", "content": VALIDATE_SYSTEM}, {"role": "user", "content": prompt}],
            max_tokens=4096,
            temperature=0.2,
        )
        result = _parse_json(raw)
        fixes = result.get("fixes", [])

        if not fixes:
            print("[validator] ✓ No issues found")
            return files, readme

        print(f"[validator] {len(fixes)} fix(es) applied:")
        for fix in fixes:
            path = fix.get("path", "")
            fixed = fix.get("fixed_content", "")
            issue = fix.get("issue", "")
            if not path or not fixed:
                continue
            print(f"  ✓ {path}: {issue}")
            if path == "README.md":
                readme = fixed
            elif path in files:
                files[path] = fixed

        return files, readme

    except Exception as e:
        print(f"[validator] Skipped (parse error): {e}")
        return files, readme


# ── Entry point ───────────────────────────────────────────────────────────────

def generate_project(analysis: dict) -> dict:
    print(f"[generator] Category: {analysis['category']} → applying style profile")
    has_source = bool(analysis.get("_source_context", {}).get("source_files"))
    print(f"[generator] Source code reference: {'yes' if has_source else 'no (README only)'}")

    print("[generator] Phase 1: Planning architecture...")
    plan = plan_project(analysis)

    file_tree = plan.get("file_tree", [])
    print(f"[generator] Planned {len(file_tree)} files:")
    for f in file_tree:
        print(f"  • {f['path']}")

    print("\n[generator] Phase 2: Writing files...")
    files: dict[str, str] = {}

    for i, spec in enumerate(file_tree):
        path = spec["path"]
        purpose = spec["purpose"]
        print(f"  [{i+1}/{len(file_tree)}] {path}")
        try:
            files[path] = generate_file(path, purpose, plan, analysis, files)
        except Exception as e:
            print(f"  ⚠ Failed {path}: {e}")
            files[path] = f"# {path}\n# {purpose}\n"
        time.sleep(4)

    readme = files.pop("README.md", f"# {plan['repo_name']}\n\n{plan['description']}\n")

    print("\n[generator] Phase 3: Validation pass...")
    files, readme = validate_and_fix(files, readme, plan, analysis)

    print(f"\n[generator] ✓ {len(files)} files ready (+README)")

    return {
        "repo_name": plan["repo_name"],
        "description": plan["description"],
        "topics": plan.get("topics", []),
        "readme": readme,
        "files": files,
        "inspired_by": analysis["source_repo"],
        "inspired_by_url": analysis["source_url"],
        "category": analysis["category"],
    }
